---
- name: Apply minishift admin-user addon
  command: "minishift addons apply admin-user"
  when: minishift_addons['admin_user']

- name: Apply minishift admissions-webhook addon
  command: "minishift addons apply admissions-webhook"
  when: minishift_addons['admissions_webhook']

- name: Apply minishift anyuid addon
  command: "minishift addons apply anyuid"
  when: minishift_addons['anyuid']

- name: Apply minishift che addon
  command: "minishift addons apply che"
  when: minishift_addons['che']

- name: Apply minishift htpasswd-identity-provider addon
  command: "minishift addons apply htpasswd-identity-provider"
  when: minishift_addons['htpasswd_identity_provider']

- name: Apply minishift redhat-registry-logon addon
  command: "minishift addons apply --addon-env REGISTRY_USERNAME={{ minishift_redhat_login }} --addon-env REGISTRY_PASSWORD={{ minishift_redhat_password }} redhat-registry-logon"
  when: minishift_addons['redhat_registry_logon']

- name: Apply minishift registry-route addon
  command: "minishift addons apply registry-route"
  when: minishift_addons['registry_route']

- name: Apply minishift xpaas addon
  command: "minishift addons apply xpaas"
  when: minishift_addons['xpaas']

#Community Addons
- name: Enable minishift grafana addon
  command: "minishft addons enable grafana"
  when: minishift_addons_community['grafana']

- name: Apply minishift grafana addon
  command: "minishift addons apply grafana --addon-env namespace=grafana"
  when: minishift_addons_community['grafana']

- name: Enable minishift prometheus addon
  command: "minishft addons enable prometheus"
  when: minishift_addons_community['prometheus']

- name: Apply minishift prometheus addon
  command: "minishift addons apply prometheus --addon-env namespace=kube-system"
  when: minishift_addons_community['prometheus']