- name: Add to insecure registry
  fail:
    block:
    - debug:
        var: output.stdout_lines
    - debug:
        msg: "Add the above IP range and '{{ openshift_hostname }}' to your Docker insecure registry settings, and then re-run this palybook."
  when:
    - output.failed is defined
    - output.failed
    - ('insecure-registry' in output.stdout)

- name: Bring up Cluster
  fail:
    block:
    - debug:
        var: output.stdout_lines
    - debug:
        msg: "`oc cluster up` failed to start. Once you are able to resolve the issue, then re-run the playbook."
  when:
    - output.failed is defined
    - output.failed

- name: Show Debug
  debug:
    var: output.stdout_lines