# Darwin_driver.yml 
# Using head because it will fail with virtualbox 6 installed https://github.com/minishift/minishift/issues/3143
- name: Install docker-machine-driver-xhyve
  homebrew:
    name: docker-machine-driver-xhyve
    state: present
  when:
    - not use_hyperkit

- name: Install docker-machine-driver-hyperkit
  homebrew:
    name: hyperkit
    state: present
  when:
    - use_hyperkit

- name: Get brew prefix
  command: brew --prefix
  register: prefix
  changed_when: False

- name: Set owner and permissions for docker-machine-driver-xyhve
  become: yes
  become_user: root
  file:
    path: "{{ prefix.stdout }}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve"
    owner: root
    group: wheel
    mode: "u+s"
  when:
    - not use_hyperkit

- name: Install docker-machine-driver-hyperkit binary
  become: yes
  become_user: root
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit
    dest: /usr/local/bin/docker-machine-driver-hyperkit
    mode: "u+s"
    owner: root
    group: wheel
  when:
    - use_hyperkit