- name: Login as system:admin
  command: oc login -u system:admin
  changed_when: false

- name: Grant cluster-admin to developer
  command: oc adm policy add-cluster-role-to-user cluster-admin admin
  changed_when: false

- name: Log in as admin
  command: oc login -u admin -p admin
  changed_when: false

- name: Set the namespace to 'default'
  command: oc project default
  changed_when: false