- name: Check if minishift-addons git path exists"
  stat:
    path: "{{ minishift_addons_community_path }}/minishift-addons"
  register: git_path

- name: Clone community addons to community path
  git:
    repo: 'https://github.com/minishift/minishift-addons.git'
    dest: "{{ minishift_addons_community_path }}"
    version: master
  when: not git_path.stat.exists

- name: "Install minishift community {{ item }} addon"
  command: "minishift addons install -f {{ minishift_addons_community_path }}/minishift-addons/add-ons/{{ item }} --enable"
  when: minishift_addons_community.item is defined
  with_items:
    - dotnet
    - example
    - grafana
    - helm
    - istio
    - workshop
    - prometheus

- name: Install minishift community ansible-service-broker addon
  command: "minishift addons install -f {{ minishift_addons_community_path }}/minishift-addons/add-ons/ansible-service-broker --enable"
  when: minishift_addons_community['ansible_service_broker']

- name: Install minishift community management-infra addon
  command: "minishift addons install -f {{ minishift_addons_community_path }}/minishift-addons/add-ons/management-infra --enable"
  when: minishift_addons_community['management_infra']

- name: Install minishift community eap-cd addon
  command: "minishift addons install -f {{ minishift_addons_community_path }}/minishift-addons/add-ons/eap-cd --enable"
  when: minishift_addons_community['eap_cd']