- name: Check if minishift-addons git path exists"
  stat:
    path: "{{ minishift_addons_community_path }}/minishift-addons"
  register: git_path

- name: Clone community addons to community path
  git:
    repo: 'https://github.com/minishift/minishift-addons.git'
    dest: "{{ minishift_addons_community_path }}"
    version: master
  when: not git_path.stat.exists

- name: "Install minishift community {{item}} addon"
  command: "minishift addons install {{ minishift_addons_community_path }}/minishift-addons/{{ item }}/{{ item }}.addon"
  when: "minishift_addons_community['{{ item }}']"
  with_items:
    - dotnet
    - example
    - grafana
    - helm
    - istio
    - workshop

- name: Install minishift community ansible-server-broker addon
  command: "minishift addons install {{ minishift_addons_community_path }}/minishift-addons/ansible-server-broker/ansible-server-broker.addon"
  when: minishift_addons_community['ansible_server_broker']

- name: Install minishift community management-infra addon
  command: "minishift addons install {{ minishift_addons_community_path }}/minishift-addons/management-infra/management-infra.addon"
  when: minishift_addons_community['management_infra']

- name: Install minishift community eap-cd addon
  command: "minishift addons install {{ minishift_addons_community_path }}/minishift-addons/eap-cd/eap-cd.addon"
  when: minishift_addons_community['eap_cd']

- name: "Enable minishift community {{item}} addon"
  command: "minishift addons enable {{ item }}"
  when: "minishift_addons_community['{{ item }}']"
  with_items:
    - dotnet
    - example
    - grafana
    - helm
    - istio
    - workshop

- name: Enable minishift community ansible-server-broker addon
  command: "minishift addons enable ansible-server-broker"
  when: minishift_addons_community['ansible_server_broker']

- name: Enable minishift community management-infra addon
  command: "minishift addons enable management-infra"
  when: minishift_addons_community['management_infra']

- name: Enable minishift community eap-cd addon
  command: "minishift addons enable eap-cd"
  when: minishift_addons_community['eap_cd']