- name: Clone community addons to community path
  git:
    repo: 'https://github.com/minishift/minishift-addons.git'
    dest: "{{ minishift_addons_community_path }}"
    version: master
  register: git_addons

- name: Install minishift community addons
  command: "minishift addons install {{ git_addons.git_dir_now }}/{{ item }}/{{ item }}.addon"
  when: minishift_addons_community['item']
  with_items:
    - dotnet
    - example
    - grafana
    - helm
    - istio
    - workshop

- name: Install minishift community ansible-server-broker addon
  command: "minishift addons install {{ git_addons.git_dir_now }}/ansible-server-broker/ansible-server-broker.addon"
  when: minishift_addons_community['ansible_server_broker']

- name: Install minishift community management-infra addon
  command: "minishift addons install {{ git_addons.git_dir_now }}/management-infra/management-infra.addon"
  when: minishift_addons_community['management_infra']

- name: Install minishift community eap-cd addon
  command: "minishift addons install {{ git_addons.git_dir_now }}/eap-cd/eap-cd.addon"
  when: minishift_addons_community['eap_cd']